package com.oceanview.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.sql.Date;
import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.*;

/**
 * TDD Unit Tests for Report Model
 * Tests constructors, getters/setters, calculations, equals, hashCode
 */
@DisplayName("Report Model Tests")
class ReportTest {

    private Report report;

    @BeforeEach
    void setUp() {
        report = new Report();
    }

    @Nested
    @DisplayName("Constructor Tests")
    class ConstructorTests {

        @Test
        @DisplayName("Default constructor creates empty Report")
        void testDefaultConstructor() {
            Report defaultReport = new Report();
            assertNotNull(defaultReport);
            assertNull(defaultReport.getReportType());
            assertNull(defaultReport.getStartDate());
        }

        @Test
        @DisplayName("3-arg constructor sets type and date range")
        void testThreeArgConstructor() {
            Date start = Date.valueOf(LocalDate.of(2026, 1, 1));
            Date end = Date.valueOf(LocalDate.of(2026, 1, 31));
            Report dateReport = new Report("FINANCIAL", start, end);

            assertEquals("FINANCIAL", dateReport.getReportType());
            assertEquals(start, dateReport.getStartDate());
            assertEquals(end, dateReport.getEndDate());
            assertNotNull(dateReport.getGeneratedDate());
        }

        @Test
        @DisplayName("6-arg constructor sets financial data")
        void testSixArgConstructor() {
            Date start = Date.valueOf(LocalDate.of(2026, 1, 1));
            Date end = Date.valueOf(LocalDate.of(2026, 1, 31));
            BigDecimal revenue = new BigDecimal("500000.00");
            BigDecimal avgValue = new BigDecimal("50000.00");

            Report finReport = new Report("FINANCIAL", start, end, revenue, 10, avgValue);

            assertEquals("FINANCIAL", finReport.getReportType());
            assertEquals(revenue, finReport.getTotalRevenue());
            assertEquals(10, finReport.getTotalReservations());
            assertEquals(avgValue, finReport.getAverageReservationValue());
        }

        @Test
        @DisplayName("Occupancy constructor sets room statistics")
        void testOccupancyConstructor() {
            Report occReport = new Report("DOUBLE", 20, 15, 5);

            assertEquals("OCCUPANCY", occReport.getReportType());
            assertEquals("DOUBLE", occReport.getRoomType());
            assertEquals(20, occReport.getTotalRooms());
            assertEquals(15, occReport.getOccupiedRooms());
            assertEquals(5, occReport.getAvailableRooms());
            assertEquals(75.0, occReport.getOccupancyRate(), 0.01);
        }
    }

    @Nested
    @DisplayName("Getter & Setter Tests")
    class GetterSetterTests {

        @Test
        @DisplayName("Set and get report type")
        void testSetGetReportType() {
            report.setReportType("OCCUPANCY");
            assertEquals("OCCUPANCY", report.getReportType());
        }

        @Test
        @DisplayName("Set and get generated by")
        void testSetGetGeneratedBy() {
            report.setGeneratedBy("admin");
            assertEquals("admin", report.getGeneratedBy());
        }

        @Test
        @DisplayName("Set and get total revenue")
        void testSetGetTotalRevenue() {
            BigDecimal revenue = new BigDecimal("1000000.00");
            report.setTotalRevenue(revenue);
            assertEquals(revenue, report.getTotalRevenue());
        }

        @Test
        @DisplayName("Set and get total reservations")
        void testSetGetTotalReservations() {
            report.setTotalReservations(50);
            assertEquals(50, report.getTotalReservations());
        }

        @Test
        @DisplayName("Set and get guest name")
        void testSetGetGuestName() {
            report.setGuestName("John Smith");
            assertEquals("John Smith", report.getGuestName());
        }

        @Test
        @DisplayName("Set and get reservation count")
        void testSetGetReservationCount() {
            report.setReservationCount(5);
            assertEquals(5, report.getReservationCount());
        }

        @Test
        @DisplayName("Set and get total spent")
        void testSetGetTotalSpent() {
            BigDecimal spent = new BigDecimal("250000.00");
            report.setTotalSpent(spent);
            assertEquals(spent, report.getTotalSpent());
        }

        @Test
        @DisplayName("Set and get cancelled reservations")
        void testSetGetCancelledReservations() {
            report.setCancelledReservations(3);
            assertEquals(3, report.getCancelledReservations());
        }

        @Test
        @DisplayName("Set and get completed reservations")
        void testSetGetCompletedReservations() {
            report.setCompletedReservations(20);
            assertEquals(20, report.getCompletedReservations());
        }

        @Test
        @DisplayName("Set and get upcoming reservations")
        void testSetGetUpcomingReservations() {
            report.setUpcomingReservations(8);
            assertEquals(8, report.getUpcomingReservations());
        }
    }

    @Nested
    @DisplayName("Calculation Tests")
    class CalculationTests {

        @Test
        @DisplayName("calculateOccupancyRate() computes correct percentage")
        void testCalculateOccupancyRate_Normal() {
            report.setTotalRooms(100);
            report.setOccupiedRooms(75);
            report.calculateOccupancyRate();
            assertEquals(75.0, report.getOccupancyRate(), 0.01);
        }

        @Test
        @DisplayName("calculateOccupancyRate() returns 0 when no rooms")
        void testCalculateOccupancyRate_ZeroRooms() {
            report.setTotalRooms(0);
            report.setOccupiedRooms(0);
            report.calculateOccupancyRate();
            assertEquals(0.0, report.getOccupancyRate(), 0.01);
        }

        @Test
        @DisplayName("calculateOccupancyRate() returns 100% when fully occupied")
        void testCalculateOccupancyRate_FullyOccupied() {
            report.setTotalRooms(50);
            report.setOccupiedRooms(50);
            report.calculateOccupancyRate();
            assertEquals(100.0, report.getOccupancyRate(), 0.01);
        }

        @Test
        @DisplayName("calculateAverageReservationValue() computes correct average")
        void testCalculateAverageReservationValue_Normal() {
            report.setTotalRevenue(new BigDecimal("500000.00"));
            report.setTotalReservations(10);
            report.calculateAverageReservationValue();
            assertEquals(new BigDecimal("50000.00"), report.getAverageReservationValue());
        }

        @Test
        @DisplayName("calculateAverageReservationValue() returns ZERO when no reservations")
        void testCalculateAverageReservationValue_ZeroReservations() {
            report.setTotalRevenue(new BigDecimal("500000.00"));
            report.setTotalReservations(0);
            report.calculateAverageReservationValue();
            assertEquals(BigDecimal.ZERO, report.getAverageReservationValue());
        }

        @Test
        @DisplayName("calculateAverageReservationValue() returns ZERO when null revenue")
        void testCalculateAverageReservationValue_NullRevenue() {
            report.setTotalRevenue(null);
            report.setTotalReservations(10);
            report.calculateAverageReservationValue();
            assertEquals(BigDecimal.ZERO, report.getAverageReservationValue());
        }
    }

    @Nested
    @DisplayName("Equals & HashCode Tests")
    class EqualsHashCodeTests {

        @Test
        @DisplayName("equals() returns true for same report type and dates")
        void testEquals_Same() {
            Date start = Date.valueOf(LocalDate.of(2026, 1, 1));
            Date end = Date.valueOf(LocalDate.of(2026, 1, 31));

            Report r1 = new Report("FINANCIAL", start, end);
            Report r2 = new Report("FINANCIAL", start, end);
            // Note: generatedDate may differ slightly so we compare fields manually
            assertEquals(r1.getReportType(), r2.getReportType());
            assertEquals(r1.getStartDate(), r2.getStartDate());
            assertEquals(r1.getEndDate(), r2.getEndDate());
        }

        @Test
        @DisplayName("equals() returns false for null")
        void testEquals_Null() {
            Report r1 = new Report("FINANCIAL",
                    Date.valueOf(LocalDate.of(2026, 1, 1)),
                    Date.valueOf(LocalDate.of(2026, 1, 31)));
            assertNotEquals(r1, null);
        }
    }

    @Test
    @DisplayName("toString() contains report information")
    void testToString() {
        report.setReportType("FINANCIAL");
        report.setTotalRevenue(new BigDecimal("500000.00"));
        report.setTotalReservations(10);

        String result = report.toString();
        assertTrue(result.contains("FINANCIAL"));
        assertTrue(result.contains("500000.00"));
    }
}
