package com.oceanview.model;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

/**
 * Report Model Class
 * Represents various reports in the OceanView Reservation System
 * 
 */
public class Report {
    
    // Private fields for general report data
    private String reportType;
    private Date startDate;
    private Date endDate;
    private String generatedBy;
    private Date generatedDate;
    
    // Financial report fields
    private BigDecimal totalRevenue;
    private int totalReservations;
    private BigDecimal averageReservationValue;
    
    // Room occupancy report fields
    private String roomType;
    private int totalRooms;
    private int occupiedRooms;
    private int availableRooms;
    private double occupancyRate;
    
    // Guest statistics fields
    private String guestName;
    private int reservationCount;
    private BigDecimal totalSpent;
    
    // Date range statistics
    private int cancelledReservations;
    private int completedReservations;
    private int upcomingReservations;
    
    /**
     * Default constructor
     */
    public Report() {
    }
    
    /**
     * Constructor for basic report
     * 
     * @param reportType type of report
     * @param startDate start date for report
     * @param endDate end date for report
     */
    public Report(String reportType, Date startDate, Date endDate) {
        this.reportType = reportType;
        this.startDate = startDate;
        this.endDate = endDate;
        this.generatedDate = new Date(System.currentTimeMillis());
    }
    
    /**
     * Constructor for financial report
     * 
     * @param reportType type of report
     * @param startDate start date
     * @param endDate end date
     * @param totalRevenue total revenue
     * @param totalReservations total number of reservations
     * @param averageReservationValue average reservation value
     */
    public Report(String reportType, Date startDate, Date endDate, 
                 BigDecimal totalRevenue, int totalReservations, 
                 BigDecimal averageReservationValue) {
        this.reportType = reportType;
        this.startDate = startDate;
        this.endDate = endDate;
        this.totalRevenue = totalRevenue;
        this.totalReservations = totalReservations;
        this.averageReservationValue = averageReservationValue;
        this.generatedDate = new Date(System.currentTimeMillis());
    }
    
    /**
     * Constructor for occupancy report
     * 
     * @param roomType room type
     * @param totalRooms total rooms
     * @param occupiedRooms occupied rooms
     * @param availableRooms available rooms
     */
    public Report(String roomType, int totalRooms, int occupiedRooms, int availableRooms) {
        this.reportType = "OCCUPANCY";
        this.roomType = roomType;
        this.totalRooms = totalRooms;
        this.occupiedRooms = occupiedRooms;
        this.availableRooms = availableRooms;
        this.occupancyRate = totalRooms > 0 ? (double) occupiedRooms / totalRooms * 100 : 0;
        this.generatedDate = new Date(System.currentTimeMillis());
    }
    
    // Getters and Setters
    
    /**
     * Get report type
     * @return report type
     */
    public String getReportType() {
        return reportType;
    }
    
    /**
     * Set report type
     * @param reportType report type
     */
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }
    
    /**
     * Get start date
     * @return start date
     */
    public Date getStartDate() {
        return startDate;
    }
    
    /**
     * Set start date
     * @param startDate start date
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    
    /**
     * Get end date
     * @return end date
     */
    public Date getEndDate() {
        return endDate;
    }
    
    /**
     * Set end date
     * @param endDate end date
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    /**
     * Get generated by
     * @return user who generated the report
     */
    public String getGeneratedBy() {
        return generatedBy;
    }
    
    /**
     * Set generated by
     * @param generatedBy user who generated the report
     */
    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }
    
    /**
     * Get generated date
     * @return date report was generated
     */
    public Date getGeneratedDate() {
        return generatedDate;
    }
    
    /**
     * Set generated date
     * @param generatedDate date report was generated
     */
    public void setGeneratedDate(Date generatedDate) {
        this.generatedDate = generatedDate;
    }
    
    /**
     * Get total revenue
     * @return total revenue
     */
    public BigDecimal getTotalRevenue() {
        return totalRevenue;
    }
    
    /**
     * Set total revenue
     * @param totalRevenue total revenue
     */
    public void setTotalRevenue(BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }
    
    /**
     * Get total reservations
     * @return total reservations
     */
    public int getTotalReservations() {
        return totalReservations;
    }
    
    /**
     * Set total reservations
     * @param totalReservations total reservations
     */
    public void setTotalReservations(int totalReservations) {
        this.totalReservations = totalReservations;
    }
    
    /**
     * Get average reservation value
     * @return average reservation value
     */
    public BigDecimal getAverageReservationValue() {
        return averageReservationValue;
    }
    
    /**
     * Set average reservation value
     * @param averageReservationValue average reservation value
     */
    public void setAverageReservationValue(BigDecimal averageReservationValue) {
        this.averageReservationValue = averageReservationValue;
    }
    
    /**
     * Get room type
     * @return room type
     */
    public String getRoomType() {
        return roomType;
    }
    
    /**
     * Set room type
     * @param roomType room type
     */
    public void setRoomType(String roomType) {
        this.roomType = roomType;
    }
    
    /**
     * Get total rooms
     * @return total rooms
     */
    public int getTotalRooms() {
        return totalRooms;
    }
    
    /**
     * Set total rooms
     * @param totalRooms total rooms
     */
    public void setTotalRooms(int totalRooms) {
        this.totalRooms = totalRooms;
    }
    
    /**
     * Get occupied rooms
     * @return occupied rooms
     */
    public int getOccupiedRooms() {
        return occupiedRooms;
    }
    
    /**
     * Set occupied rooms
     * @param occupiedRooms occupied rooms
     */
    public void setOccupiedRooms(int occupiedRooms) {
        this.occupiedRooms = occupiedRooms;
    }
    
    /**
     * Get available rooms
     * @return available rooms
     */
    public int getAvailableRooms() {
        return availableRooms;
    }
    
    /**
     * Set available rooms
     * @param availableRooms available rooms
     */
    public void setAvailableRooms(int availableRooms) {
        this.availableRooms = availableRooms;
    }
    
    /**
     * Get occupancy rate
     * @return occupancy rate as percentage
     */
    public double getOccupancyRate() {
        return occupancyRate;
    }
    
    /**
     * Set occupancy rate
     * @param occupancyRate occupancy rate as percentage
     */
    public void setOccupancyRate(double occupancyRate) {
        this.occupancyRate = occupancyRate;
    }
    
    /**
     * Get guest name
     * @return guest name
     */
    public String getGuestName() {
        return guestName;
    }
    
    /**
     * Set guest name
     * @param guestName guest name
     */
    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }
    
    /**
     * Get reservation count
     * @return reservation count
     */
    public int getReservationCount() {
        return reservationCount;
    }
    
    /**
     * Set reservation count
     * @param reservationCount reservation count
     */
    public void setReservationCount(int reservationCount) {
        this.reservationCount = reservationCount;
    }
    
    /**
     * Get total spent by guest
     * @return total spent
     */
    public BigDecimal getTotalSpent() {
        return totalSpent;
    }
    
    /**
     * Set total spent by guest
     * @param totalSpent total spent
     */
    public void setTotalSpent(BigDecimal totalSpent) {
        this.totalSpent = totalSpent;
    }
    
    /**
     * Get cancelled reservations
     * @return cancelled reservations
     */
    public int getCancelledReservations() {
        return cancelledReservations;
    }
    
    /**
     * Set cancelled reservations
     * @param cancelledReservations cancelled reservations
     */
    public void setCancelledReservations(int cancelledReservations) {
        this.cancelledReservations = cancelledReservations;
    }
    
    /**
     * Get completed reservations
     * @return completed reservations
     */
    public int getCompletedReservations() {
        return completedReservations;
    }
    
    /**
     * Set completed reservations
     * @param completedReservations completed reservations
     */
    public void setCompletedReservations(int completedReservations) {
        this.completedReservations = completedReservations;
    }
    
    /**
     * Get upcoming reservations
     * @return upcoming reservations
     */
    public int getUpcomingReservations() {
        return upcomingReservations;
    }
    
    /**
     * Set upcoming reservations
     * @param upcomingReservations upcoming reservations
     */
    public void setUpcomingReservations(int upcomingReservations) {
        this.upcomingReservations = upcomingReservations;
    }
    
    /**
     * Calculate occupancy rate
     */
    public void calculateOccupancyRate() {
        if (totalRooms > 0) {
            this.occupancyRate = (double) occupiedRooms / totalRooms * 100;
        } else {
            this.occupancyRate = 0;
        }
    }
    
    /**
     * Calculate average reservation value
     */
    public void calculateAverageReservationValue() {
        if (totalReservations > 0 && totalRevenue != null) {
            this.averageReservationValue = totalRevenue.divide(
                BigDecimal.valueOf(totalReservations), 
                2, 
                java.math.RoundingMode.HALF_UP
            );
        } else {
            this.averageReservationValue = BigDecimal.ZERO;
        }
    }
    
    @Override
    public String toString() {
        return "Report{" +
                "reportType='" + reportType + '\'' +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                ", generatedBy='" + generatedBy + '\'' +
                ", generatedDate=" + generatedDate +
                ", totalRevenue=" + totalRevenue +
                ", totalReservations=" + totalReservations +
                ", averageReservationValue=" + averageReservationValue +
                ", roomType='" + roomType + '\'' +
                ", totalRooms=" + totalRooms +
                ", occupiedRooms=" + occupiedRooms +
                ", availableRooms=" + availableRooms +
                ", occupancyRate=" + occupancyRate +
                ", guestName='" + guestName + '\'' +
                ", reservationCount=" + reservationCount +
                ", totalSpent=" + totalSpent +
                '}';
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Report report = (Report) o;
        return Objects.equals(reportType, report.reportType) &&
               Objects.equals(startDate, report.startDate) &&
               Objects.equals(endDate, report.endDate) &&
               Objects.equals(generatedDate, report.generatedDate);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(reportType, startDate, endDate, generatedDate);
    }
}
